name: Semgrep

on:
  pull_request: {}
  push:
    branches:
    - main
    - master

jobs:
  semgrep:
    name: Semgrep scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        config: >-
          p/security-audit
          p/secrets
        # publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
        generateSarif: "1"
        # auditOn: push
        
    # Upload findings to GitHub Advanced Security Dashboard [step 2/2]
    - name: Upload SARIF file for GitHub Advanced Security Dashboard
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: semgrep.sarif
      if: always()

        
